### ISSUE TITLE
Trailing comma gives error in Angular 5 object

### ISSUE THREAD

**Issue by ns-rickvdmeij** [AanZee/styleguides#18]
When building an object for ngClass and use trailing commas, I'll get the following:

code:
```html
      <div class="input-box__status-indicator"
		[ngClass]="{
			'is-valid': isValid,
			'is-invalid': isInvalid,
		}"
	></div>
```

error:
```js
compiler.js:485 Uncaught Error: Template parse errors:
Parser Error: Unexpected token }, expected identifier, keyword, or string at column 57 in [{
			'is-valid': isValid,
			'is-invalid': isInvalid,
		}] in ng:///InputBoxModule/InputBoxComponent.html@16:2 ("
	</div>
	<div class="input-box__status-indicator"
		[ERROR ->][ngClass]="{
			'is-valid': isValid,
			'is-invalid': isInvalid,
"): ng:///InputBoxModule/InputBoxComponent.html@16:2
```

This means the convention should be erased

**Comment by 7img** [comment]
I don't think we should remove an entire convention just because you've found an exception 😜 ,

**Comment by ns-rickvdmeij** [comment]
It does say 'Right' and 'Wrong': https://github.com/AanZee/conventions/blob/master/general/README.md#trailing-commas

In this case there is no wrong. So maybe don't remove it, but at least change it to something like 
'Do' and 'Do when trailing comma won't work'

**Comment by 7img** [comment]
> Use trailing commas in arrays, objects, functions, methods, imports and exports **when valid syntax in your language**.

I don't mind skipping it in Angular HTML templates as long as we can still use it in imports.

**Comment by edgargressie** [comment]
I agree with @7img. Right or wrong only counts when it's a valid syntax in your code. Can we close this issue @rickvandermeij-aanzee?
