### ISSUE TITLE
Write variables in camelCase

### ISSUE THREAD

**Issue by 7img** [AanZee/styleguides#4]
https://github.com/AanZee/conventions/blob/master/javascript/README.md#write-variables-in-camelcase

Kunnen we hier een uitzondering voor toevoegen als we een Object shorthand gebruiken voor bijvoorbeeld Headers ? Zie Origin:

```js
	static generateHeaders(headers: any) {
		const Origin = window.location.origin ? window.location.origin : 'https://www.hellokitty.com';

		return new Headers(Object.assign({
			// Default headers
			'Content-Type': 'text/plain',
			Origin,
		}, headers));
	}
```

**Comment by rsdebest** [comment]
Het lijkt me wel toch? Er vanuitgaande dat 'content-type' en 'origin' incorrect zijn vanwege case sensitivity aan de ontvangende kant.

**Comment by stevengunneweg** [comment]
Waarom kunnen we in dit geval niet het volgende aanhouden?
```js
	static generateHeaders(headers: any) {
		const origin = window.location.origin ? window.location.origin : 'https://example.com';

		return new Headers(Object.assign({
			// Default headers
			'Content-Type': 'text/plain',
			Origin: origin,
		}, headers));
	}
```

**Comment by edgargressie** [comment]
Kunnen we in dit soort gevallen de object shorthand niet laten vallen? Dit komt niet vaak voor en bij elke uitzondering die we op de regel bedenken wordt het alleen maar complexer.

```js
	static generateHeaders(headers: any) {
		const origin = window.location.origin ? window.location.origin : 'https://example.com';

		return new Headers(Object.assign({
			// Default headers
			'Content-Type': 'text/plain',
			Origin: origin,
		}, headers));
	}
```

**Comment by 7img** [comment]
Eens, is misschien duidelijker om in dat geval de object shorthand te laten vervallen.

**Comment by edgargressie** [comment]
Top, dan sluit ik hem voor nu
